core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounting.urls', namespace='accounting')),
    path('', include('student.urls', namespace='student')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from .parameters_views import (
    ClassListView,
    ClassListCreateView,
    ClassListUpdateView,
    DeleteClassListView,
    YearListView,
    YearCreateView,
    YearUpdateView,
    DeleteYearListView,
    reorder_years,
    GroupDeleteView,
    GroupUpdateView,
    GroupCreateView,
    GroupListView, SubjectDeleteView, SubjectUpdateView, SubjectCreateView, SubjectListView, ExamListView,
    ExamCreateView, ExamUpdateView, ExamDeleteView, ClassNumberListView, ClassNumberCreateView, ClassNumberUpdateView,
    ClassNumberDeleteView, PositionListView, PositionCreateView, PositionUpdateView, PositionDeleteView,
    ProximityListView, ProximityCreateView, ProximityUpdateView, ProximityDeleteView
)
from .report_views import (
    LatePaymentListView, ExportLatePaymentsExcelView, DailyPayments, ExportDailyPaymentsExcelView,
    StudentReportListView, ExportStudentReportExcelView

)
from .views import (
    CreateStudentView,
    StudentListView,
    SplitTuitionFeeView,
    TuitionFeeSplitDetailView,
    refund_payment,
    PaymentReceiptView,
    save_splits,
    make_payment,
    export_students,
    RepeatRegistrationSearchView,
    RepeatRegistrationCreateView, calculate_fee, StudentUpdateView, download_contract, StudentDeleteConfirm,
    tuition_fee_schedule_view
)

app_name = 'student'
urlpatterns = [
    # STUDENT
    path('student_list/', StudentListView.as_view(), name='student_list'),
    path('add_student/', CreateStudentView.as_view(), name='add_student'),
    path('update_student/<int:pk>/', StudentUpdateView.as_view(), name='update_student'),
    path('repeat_registration_search/', RepeatRegistrationSearchView.as_view(),
         name='repeat_registration_search'),
    path('repeat_registration_create/<int:student_id>/', RepeatRegistrationCreateView.as_view(),
         name='repeat_registration_create'),
    path('export_students/', export_students, name='export_students'),
    path('calculate-fee/', calculate_fee, name='calculate_fee'),
    path('student/<int:student_id>/download_contract/', download_contract, name='download_contract'),
    path('student_delete_confirm/<int:pk>/', StudentDeleteConfirm.as_view(), name='student_delete_confirm'),

    # PAYMENT
    path('student/<int:student_id>/split/', SplitTuitionFeeView.as_view(), name='split_tuition_fee'),
    path('student/split/<int:student_id>/', TuitionFeeSplitDetailView.as_view(), name='tuition_fee_split_detail'),
    path('student/make_payment/<int:split_id>/', make_payment, name='make_payment'),

    path('student/refund_payment/<int:split_id>/', refund_payment, name='refund_payment'),
    path('student/payment_receipt/<int:split_id>/', PaymentReceiptView.as_view(), name='payment_receipt'),
    path('student/save_splits/<int:student_id>/', save_splits, name='save_splits'),
    path('students/<int:student_id>/tuition-fee-schedule/', tuition_fee_schedule_view, name='tuition_fee_schedule'),

    # PARAMETERS
    # ***CLASS-LIST***
    path('class_list/', ClassListView.as_view(), name='class_list'),
    path('add_class/', ClassListCreateView.as_view(), name='add_class'),
    path('update_class/<int:pk>/', ClassListUpdateView.as_view(), name='update_class'),
    path('delete_confirm_class/<int:pk>/', DeleteClassListView.as_view(), name='delete_confirm_class'),

    # ***YEAR-LIST***
    path('year_list/', YearListView.as_view(), name='year_list'),
    path('add_year/', YearCreateView.as_view(), name='add_year'),
    path('update_year/<int:pk>/', YearUpdateView.as_view(), name='update_year'),
    path('delete_year/<int:pk>/', DeleteYearListView.as_view(), name='delete_year'),
    path('reorder_years/', reorder_years, name='reorder_years'),

    # GROUP
    path('group_list/', GroupListView.as_view(), name='group_list'),
    path('add_group/', GroupCreateView.as_view(), name='add_group'),
    path('update_group/<int:pk>/', GroupUpdateView.as_view(), name='update_group'),
    path('delete_confirm_group/<int:pk>/', GroupDeleteView.as_view(), name='delete_confirm_group'),

    # FƏNN
    path('subject_list/', SubjectListView.as_view(), name='subject_list'),
    path('add_subject/', SubjectCreateView.as_view(), name='add_subject'),
    path('update_subject/<int:pk>/', SubjectUpdateView.as_view(), name='update_subject'),
    path('delete_confirm_subject/<int:pk>/', SubjectDeleteView.as_view(), name='delete_confirm_subject'),

    # EXAM
    path('exam_list/', ExamListView.as_view(), name='exam_list'),
    path('add_exam/', ExamCreateView.as_view(), name='add_exam'),
    path('update_exam/<int:pk>/', ExamUpdateView.as_view(), name='update_exam'),
    path('delete_confirm_exam/<int:pk>/', ExamDeleteView.as_view(), name='delete_confirm_exam'),

    # CLASS-NUMBER
    path('class_number_list/', ClassNumberListView.as_view(), name='class_number_list'),
    path('add_class_number/', ClassNumberCreateView.as_view(), name='add_class_number'),
    path('update_class_number/<int:pk>/', ClassNumberUpdateView.as_view(), name='update_class_number'),
    path('delete_confirm_class_number/<int:pk>/', ClassNumberDeleteView.as_view(), name='delete_confirm_class_number'),

    # POSITIONS
    path('positions_list/', PositionListView.as_view(), name='positions_list'),
    path('add_position/', PositionCreateView.as_view(), name='add_position'),
    path('update_position/<int:pk>/', PositionUpdateView.as_view(), name='update_position'),
    path('delete_confirm_position/<int:pk>/', PositionDeleteView.as_view(), name='delete_confirm_position'),

    # PROXIMITY
    path('proximity_list/', ProximityListView.as_view(), name='proximity_list'),
    path('add_proximity/', ProximityCreateView.as_view(), name='add_proximity'),
    path('update_proximity/<int:pk>/', ProximityUpdateView.as_view(), name='update_proximity'),
    path('delete_confirm_proximity/<int:pk>/', ProximityDeleteView.as_view(), name='delete_confirm_proximity'),

    # REPORT
    path('late_payments/', LatePaymentListView.as_view(), name='late_payments'),
    path('export_late_payments/', ExportLatePaymentsExcelView.as_view(), name='export_late_payments'),
    path('daly_payments/', DailyPayments.as_view(), name='daly_payments'),
    path('export_daily_payments/', ExportDailyPaymentsExcelView.as_view(), name='export_daily_payments'),
    path('student_report/', StudentReportListView.as_view(), name='student_report'),
    path('export_student_report/', ExportStudentReportExcelView.as_view(), name='export_student_report'),
]

student/forms.py
from django import forms

from .models import (
    Student,
    StudentClass,
    Year,
    Group, Subject, Exam, ClassNumber, Position, Proximity
)


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'first_name',
            'last_name',
            'gender',
            'shift',
            'note',
            'student_class',
            'group',
            'section',
            'score',
            'registration_status',
            'class_number',
            'subject',
            'exam',
            'school',
            'city',
            'address',
            'father_first_name',
            'father_last_name',
            'father_workplace',
            'father_position',
            'father_phone_1',
            'father_phone_2',
            'mather_first_name',
            'mather_last_name',
            'mather_workplace',
            'mather_position',
            'mather_phone_1',
            'mather_phone_2',
            'responsible_first_name',
            'responsible_last_name',
            'responsible_sur_name',
            'responsible_address',
            'responsible_passport_number',
            'responsible_fin',
            'responsible_workplace',
            'responsible_position',
            'proximity',
            'responsible_phone_1',
            'responsible_phone_2',
            'concession_1',
            'concession_1_price',
            'concession_2',
            'concession_2_price',
            'concession_3',
            'concession_3_price',
            'concession_1_percent',
            'concession_2_percent',
            'concession_3_percent',
            'total_concession',
            'annual_fee',
        ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'shift': forms.Select(attrs={'class': 'form-control'}),
            'note': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'student_class': forms.Select(attrs={'class': 'form-control', 'id': 'id_student_class'}),
            'group': forms.Select(attrs={'class': 'form-control', 'id': 'id_group'}),
            'registration_status': forms.Select(attrs={'class': 'form-control'}),
            'section': forms.Select(attrs={'class': 'form-control'}),
            'score': forms.NumberInput(attrs={'class': 'form-control'}),
            'class_number': forms.Select(attrs={'class': 'form-control'}),
            'subject': forms.SelectMultiple(
                attrs={'class': 'form-control', 'multiple': 'multiple', 'id': 'id_subject'}),
            'exam': forms.SelectMultiple(attrs={'class': 'form-control', 'multiple': 'multiple', 'id': 'id_exam'}),
            'school': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),

            'father_first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'father_last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'father_workplace': forms.TextInput(attrs={'class': 'form-control'}),
            'father_position': forms.Select(attrs={'class': 'form-control'}),
            'father_phone_1': forms.TextInput(attrs={'class': 'form-control phone-input', 'type': 'tel', 'maxlength': '16', 'placeholder': '(055) 555 55 55'}),
            'father_phone_2': forms.TextInput(attrs={'class': 'form-control phone-input', 'type': 'tel', 'maxlength': '16', 'placeholder': '(055) 555 55 55'}),

            'mather_first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'mather_last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'mather_workplace': forms.TextInput(attrs={'class': 'form-control'}),
            'mather_position': forms.Select(attrs={'class': 'form-control'}),
            'mather_phone_1': forms.TextInput(attrs={'class': 'form-control phone-input', 'type': 'tel', 'maxlength': '16', 'placeholder': '(055) 555 55 55'}),
            'mather_phone_2': forms.TextInput(attrs={'class': 'form-control phone-input', 'type': 'tel', 'maxlength': '16', 'placeholder': '(055) 555 55 55'}),

            'responsible_first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'responsible_last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'responsible_sur_name': forms.TextInput(attrs={'class': 'form-control'}),
            'responsible_passport_number': forms.TextInput(attrs={'class': 'form-control limited-input-11', 'placeholder': 'AA / AZE'}),
            'responsible_fin': forms.TextInput(attrs={'class': 'form-control limited-input', 'maxlength': '7'}),
            'responsible_address': forms.TextInput(attrs={'class': 'form-control'}),
            'responsible_workplace': forms.TextInput(attrs={'class': 'form-control'}),
            'responsible_position': forms.Select(attrs={'class': 'form-control'}),
            'proximity': forms.Select(attrs={'class': 'form-control'}),
            'responsible_phone_1': forms.TextInput(attrs={'class': 'form-control phone-input', 'type': 'tel', 'maxlength': '16', 'placeholder': '(055) 555 55 55'}),
            'responsible_phone_2': forms.TextInput(attrs={'class': 'form-control phone-input', 'type': 'tel', 'maxlength': '16', 'placeholder': '(055) 555 55 55'}),

            'concession_1': forms.TextInput(attrs={'class': 'form-control'}),
            'concession_1_price': forms.NumberInput(attrs={'class': 'form-control', 'id': 'id_concession_1_price'}),
            'concession_2': forms.TextInput(attrs={'class': 'form-control'}),
            'concession_2_price': forms.NumberInput(attrs={'class': 'form-control', 'id': 'id_concession_2_price'}),
            'concession_3': forms.TextInput(attrs={'class': 'form-control'}),
            'concession_3_price': forms.NumberInput(attrs={'class': 'form-control', 'id': 'id_concession_3_price'}),

            'total_concession': forms.NumberInput(attrs={'class': 'form-control', 'id': 'total_concession'}),

            'concession_1_percent': forms.NumberInput(attrs={'class': 'form-control', 'id': 'concession_1_percent'}),
            'concession_2_percent': forms.NumberInput(attrs={'class': 'form-control', 'id': 'concession_2_percent'}),
            'concession_3_percent': forms.NumberInput(attrs={'class': 'form-control', 'id': 'concession_3_percent'}),
            'annual_fee': forms.NumberInput(
                attrs={'class': 'form-control', 'id': 'id_annual_fee'}),
        }


class StudentSearchForm(forms.Form):
    first_name = forms.CharField(required=False, label='Ad')
    last_name = forms.CharField(required=False, label='Soyad')
    work_number = forms.CharField(required=False, label='İş nömrəsi')


class SplitTuitionFeeForm(forms.Form):
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
                                 label="Start Date")
    number_of_months = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}), min_value=1,
                                          label="Number of Months")


class ClassForm(forms.ModelForm):
    class Meta:
        model = StudentClass
        fields = ['name', 'price']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class YearForm(forms.ModelForm):
    class Meta:
        model = Year
        fields = ['year', 'order']
        widgets = {
            'year': forms.TextInput(attrs={'class': 'form-control'}),
            'order': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'price']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['name', 'price']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class ExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ['name', 'price']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class ClassNumberForm(forms.ModelForm):
    class Meta:
        model = ClassNumber
        fields = ['number']
        widgets = {
            'number': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class PositionForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ProximityForm(forms.ModelForm):
    class Meta:
        model = Proximity
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }

student/templates/student/split_tuition_fee.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Taksidlərə bölünmə
{% endblock %}
{% block content %}
<div class="container">
    <ol class="breadcrumb text-white bg-secondary bg-gradient border-0">
        <li class="breadcrumb-item"><a href="{% url 'student:student_list' %}"><span>ŞAGİRD CƏDVƏLİ</span></a></li>
        <li class="breadcrumb-item"><a href="{% url 'student:student_list' %}"><span>ŞAGİRD CƏDVƏLİ</span></a>
        <li class="breadcrumb-item text-secondary"><span>TƏHSİL HAQQININ BÖLÜNMƏSİ</span></li>
    </ol>
    <h2 class="text-center">{{ student.first_name }} {{ student.last_name }} <br> Təhsil haqqının bölünməsi</h2>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12">
                <form method="post" class="needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col-md-6 mb-3">
                            <label for="id_start_date" class="form-label">İlkin ödəniş tarixi</label>
                            {{ form.start_date }}
                            <div class="invalid-feedback">Tarix seçin!</div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_number_of_months" class="form-label">Taksit sayı</label>
                            {{ form.number_of_months }}
                            <div class="invalid-feedback">Bu sahə vacibdir!</div>
                        </div>
                    </div>
                    <div class="text-center">
                        <button class="btn btn-success btn-sm" type="submit">Yadda saxla</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock %}

student/templates/student/tuition_fee_split_detail.html
{% extends 'base.html' %}
{% block title %}
Ödəniş cədvəli
{% endblock %}
{% block content %}
{% include 'accounting/inc/_messages.html' %}
<div class="container mt-4">
        <ol class="breadcrumb text-white bg-secondary bg-gradient border-0">
        <li class="breadcrumb-item"><a href="{% url 'student:student_list' %}"><span>ŞAGİRD CƏDVƏLİ</span></a></li>
        <li class="breadcrumb-item text-secondary"><span>TAKSİT MƏLUMATLARI</span></li>
    </ol>
    <h2>Taksit məlumatları {{ student.first_name }} {{ student.last_name }}</h2>
    <p>Sinif: {{ student.student_class }} - Qrup: {{ student.group }} - İş nömrəsi: {{ student.work_number }}</p>
    <div class="row mb-4">
        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item">İllik təhsil haqqı: <strong class="text-end">{{ annual_fee|stringformat:"0.2f" }} ₼ </strong></li>
                <li class="list-group-item">Ödənilən məbləğ: <strong>{{ total_paid|stringformat:"0.2f" }} ₼ </strong></li>
                <li class="list-group-item">Qalan məbləğ: <strong>{{ remaining_amount|stringformat:"0.2f" }} ₼ </strong></li>
                <li class="list-group-item">Gecikən məbləğ: <strong>{% if overdue_amount > 0 %} {{ overdue_amount|stringformat:"0.2f" }} ₼ {% else %} 0 ₼{% endif %}</strong></li>
            </ul>
        </div>
        <div class="col-md-6">
            {% if next_payment_date and next_payment_amount is not None %}
            <ul class="list-group">
                <li class="list-group-item">Növbəti ödəniş tarixi: <strong>{{ next_payment_date|date:'d.m.Y' }}</strong></li>
                <li class="list-group-item">Növbəti ödəniş məbləği: <strong>{{ next_payment_amount|stringformat:"0.2f" }} ₼</strong></li>
            {% else %}
            <li class="list-group-item">Növbəti ödəniş tarixi: <strong>Ödəniş bitib</strong></li>
            <li class="list-group-item">Növbəti ödəniş məbləği: <strong>Ödəniş bitib</strong></li>
            </ul>
            {% endif %}
        </div>
    </div>
    <hr>

    <div class="row">
    <div class="col">
    <div class="col-md-12">
        <div class="table-responsive text-nowrap">
        <form method="post" action="{% url 'student:save_splits' student.id %}" id="saveSplitsForm">
            <div class="mb-3 text-end">
                <a href="{% url 'student:tuition_fee_schedule' student.id %}" target="_blank" class="btn btn-primary btn-sm mt-2"><i class="fa fa-list"></i> Ödəniş cədvəli</a>
            <button type="button" class="btn btn-success btn-sm mt-2" id="addSplitRow"><i class="fas fa-plus-circle"></i> Sıra əlavə et</button>
            <button type="submit" class="btn btn-primary btn-sm mt-2"><i class="fas fa-save"></i> Dəyişiklikləri yadda saxla</button>
            </div>
            {% csrf_token %}
            <input type="hidden" name="deleted_splits" id="deletedSplits">
            <table class="table table-hover">
            <thead class="text-nowrap text-center text-bg-secondary">
            <tr>
                <th>#</th>
                <th>Plan üzrə tarix</th>
                <th>Plan üzrə məbləğ</th>
                <th>Ödənilən tarix</th>
                <th>Ödənilən məbləğ</th>
                <th>Qalıq borc</th>
                <th>Əməliyyatlar</th>
            </tr>
            </thead>
            <tbody id="splitsTableBody" class="text-center">
            {% for split in tuition_fee_splits %}
            <tr data-id="{{ split.id }}">
            {% if split.payment_date %}
                <td class="bg-success">{{ forloop.counter }}</td>
            {% elif split.installment_date < today %}
                <td class="bg-danger">{{ forloop.counter }}</td>
            {% else %}
                <td>{{ forloop.counter }}</td>
            {% endif %}
                <td>
                    {% if split.payment_date %}
                    <input disabled type="date" name="installment_date_{{ split.id }}" value="{{ split.installment_date|date:'Y-m-d' }}" class="form-control">
                    {% else %}
                    <input  type="date" name="installment_date_{{ split.id }}" value="{{ split.installment_date|date:'Y-m-d' }}" class="form-control">
                    {% endif %}
                </td>
                <td>
                    {% if split.payment_date %}
                    <input disabled type="number" name="installment_amount_{{ split.id }}" value="{{ split.installment_amount|stringformat:'0.2f' }}" step="0.01" class="form-control installment-amount" data-index="{{ forloop.counter0 }}">
                    {% else %}
                    <input type="number" name="installment_amount_{{ split.id }}" value="{{ split.installment_amount|stringformat:'0.2f' }}" step="0.01" class="form-control installment-amount" data-index="{{ forloop.counter0 }}">
                    {% endif %}
                </td>
                {% if split.payment_date is None %}
                <td>..../..../....</td>
                {% else %}
                <td>{{ split.payment_date|date:'d.m.Y' }}</td>
                {% endif %}
                <td>{{ split.payment_amount|stringformat:"0.2f" }} ₼</td>
                <td>{{ split.amount_due|stringformat:"0.2f" }} ₼</td>
                <td>
                    {% if not split.payment_date %}
                        {% if split.installment_date < today %}
                            <button title="Ödə"  type="submit" class="btn btn-danger btn-sm" formaction="{% url 'student:make_payment' split.id %}"><i class="fas fa-money-check"></i></button>
                        {% else %}
                            <button title="Ödə"  type="submit" class="btn btn-success btn-sm" formaction="{% url 'student:make_payment' split.id %}"><i class="fas fa-money-check"></i></button>
                        {% endif %}
                    {% else %}
                    <a title="Çap et" href="{% url 'student:payment_receipt' split.id %}" class="btn btn-info btn-sm"><i class="fas fa-print"></i></a>
                    {% if split.installment_date < today %}
                    <button disabled title="Geri ödə" type="button" class="btn btn-warning btn-sm" onclick="submitRefundForm({{ split.id }});"><i class="fas fa-redo"></i></button>
                    {% else %}
                    <button title="Geri ödə" type="button" class="btn btn-warning btn-sm" onclick="submitRefundForm({{ split.id }});"><i class="fas fa-redo"></i></button>
                    {% endif %}
                    {% endif %}
                    {% if not split.payment_date  %}
                    <button title="Sil" type="button" class="btn btn-danger btn-sm" onclick="removeSplitRow(this, {{ split.id }});"><i class="fas fa-trash"></i></button>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        </form>
        </div>
    </div>
</div>
</div>
</div>

<!-- Hidden form for refunding payments -->
<form id="refundForm" method="post" style="display:none;">
    {% csrf_token %}
</form>

<script>

function submitRefundForm(splitId) {
    const form = document.getElementById('refundForm');
    form.action = "{% url 'student:refund_payment' 0 %}".replace('/0/', '/' + splitId + '/');
    form.submit();
}

function removeSplitRow(button, splitId) {
    const row = button.closest('tr');
    row.remove();

    const deletedSplits = document.getElementById('deletedSplits');
    let deletedIds = deletedSplits.value ? deletedSplits.value.split(',') : [];
    deletedIds.push(splitId);
    deletedSplits.value = deletedIds.join(',');
}

document.addEventListener('DOMContentLoaded', function () {
    const totalAmount = parseFloat('{{ annual_fee|stringformat:"0.2f" }}');
    const installments = document.querySelectorAll('.installment-amount');

    installments.forEach(input => {
        input.addEventListener('input', function () {
            const index = parseInt(this.getAttribute('data-index'));
            let remainingAmount = totalAmount;

            // Сначала вычитаем все предыдущие суммы
            for (let i = 0; i < index; i++) {
                remainingAmount -= parseFloat(installments[i].value);
            }

            // Вычитаем текущую измененную сумму
            remainingAmount -= parseFloat(this.value);

            // Рассчитываем на оставшиеся платежи
            const remainingInstallments = installments.length - index - 1;
            if (remainingInstallments > 0) {
                const evenAmount = Math.floor(remainingAmount / remainingInstallments);
                let remainder = remainingAmount % remainingInstallments;

                // Распределить оставшуюся сумму, учитывая остаток
                for (let i = index + 1; i < installments.length; i++) {
                    let adjustment = remainder > 0 ? 1 : 0;
                    installments[i].value = (evenAmount + adjustment).toFixed(2);
                    remainder -= adjustment;
                }
            }
        });
    });
});

document.getElementById('addSplitRow').addEventListener('click', function () {
        const tableBody = document.getElementById('splitsTableBody');
        const newRow = document.createElement('tr');

        const rowCount = tableBody.rows.length + 1;

        newRow.innerHTML = `
            <td>${rowCount}</td>
            <td>
                <input type="date" name="new_installment_date_${rowCount}" class="form-control">
            </td>
            <td>
                <input type="number" name="new_installment_amount_${rowCount}" step="0.01" class="form-control installment-amount" data-index="${rowCount - 1}">
            </td>
            <td></td>
            <td></td>
            <td>
                <button type="button" class="btn btn-danger btn-sm" onclick="removeSplitRow(this, 'new_${rowCount}');"><i class="fas fa-trash"></i></button>
            </td>
        `;
        tableBody.appendChild(newRow);

        // Add event listener for the new input
        newRow.querySelector('.installment-amount').addEventListener('input', function () {
            const index = rowCount - 1;
            let remainingAmount = totalAmount;

            for (let i = 0; i < installments.length; i++) {
                if (i < index) {
                    remainingAmount -= parseFloat(installments[i].value);
                }
            }

            const newAmount = parseFloat(this.value);
            remainingAmount -= newAmount;

            const remainingInstallments = installments.length - index - 1;
            const newInstallmentAmount = (remainingAmount / remainingInstallments).toFixed(2);

            // Set the amount for the next installment
            if (remainingInstallments > 0) {
                installments[index + 1].value = (parseFloat(newInstallmentAmount) + (remainingAmount % remainingInstallments)).toFixed(2);
            }

            // Set the amounts for the rest of the installments
            for (let i = index + 2; i < installments.length; i++) {
                installments[i].value = newInstallmentAmount;
            }
        });
    });
</script>

{% endblock %}