core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounting.urls', namespace='accounting')),
    path('', include('student.urls', namespace='student')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from .parameters_views import (
    ClassListView,
    ClassListCreateView,
    ClassListUpdateView,
    DeleteClassListView,
    YearListView,
    YearCreateView,
    YearUpdateView,
    DeleteYearListView,
    reorder_years,
    GroupDeleteView,
    GroupUpdateView,
    GroupCreateView,
    GroupListView, SubjectDeleteView, SubjectUpdateView, SubjectCreateView, SubjectListView, ExamListView,
    ExamCreateView, ExamUpdateView, ExamDeleteView, ClassNumberListView, ClassNumberCreateView, ClassNumberUpdateView,
    ClassNumberDeleteView, PositionListView, PositionCreateView, PositionUpdateView, PositionDeleteView,
    ProximityListView, ProximityCreateView, ProximityUpdateView, ProximityDeleteView
)
from .report_views import (
    LatePaymentListView, ExportLatePaymentsExcelView, DailyPayments, ExportDailyPaymentsExcelView,
    StudentReportListView, ExportStudentReportExcelView

)
from .views import (
    CreateStudentView,
    StudentListView,
    SplitTuitionFeeView,
    TuitionFeeSplitDetailView,
    refund_payment,
    PaymentReceiptView,
    save_splits,
    make_payment,
    export_students,
    RepeatRegistrationSearchView,
    RepeatRegistrationCreateView, calculate_fee, StudentUpdateView, download_contract, StudentDeleteConfirm,
    tuition_fee_schedule_view
)

app_name = 'student'
urlpatterns = [
    # STUDENT
    path('student_list/', StudentListView.as_view(), name='student_list'),
    path('add_student/', CreateStudentView.as_view(), name='add_student'),
    path('update_student/<int:pk>/', StudentUpdateView.as_view(), name='update_student'),
    path('repeat_registration_search/', RepeatRegistrationSearchView.as_view(),
         name='repeat_registration_search'),
    path('repeat_registration_create/<int:student_id>/', RepeatRegistrationCreateView.as_view(),
         name='repeat_registration_create'),
    path('export_students/', export_students, name='export_students'),
    path('calculate-fee/', calculate_fee, name='calculate_fee'),
    path('student/<int:student_id>/download_contract/', download_contract, name='download_contract'),
    path('student_delete_confirm/<int:pk>/', StudentDeleteConfirm.as_view(), name='student_delete_confirm'),

    # PAYMENT
    path('student/<int:student_id>/split/', SplitTuitionFeeView.as_view(), name='split_tuition_fee'),
    path('student/split/<int:student_id>/', TuitionFeeSplitDetailView.as_view(), name='tuition_fee_split_detail'),
    path('student/make_payment/<int:split_id>/', make_payment, name='make_payment'),

    path('student/refund_payment/<int:split_id>/', refund_payment, name='refund_payment'),
    path('student/payment_receipt/<int:split_id>/', PaymentReceiptView.as_view(), name='payment_receipt'),
    path('student/save_splits/<int:student_id>/', save_splits, name='save_splits'),
    path('students/<int:student_id>/tuition-fee-schedule/', tuition_fee_schedule_view, name='tuition_fee_schedule'),

    # PARAMETERS
    # ***CLASS-LIST***
    path('class_list/', ClassListView.as_view(), name='class_list'),
    path('add_class/', ClassListCreateView.as_view(), name='add_class'),
    path('update_class/<int:pk>/', ClassListUpdateView.as_view(), name='update_class'),
    path('delete_confirm_class/<int:pk>/', DeleteClassListView.as_view(), name='delete_confirm_class'),

    # ***YEAR-LIST***
    path('year_list/', YearListView.as_view(), name='year_list'),
    path('add_year/', YearCreateView.as_view(), name='add_year'),
    path('update_year/<int:pk>/', YearUpdateView.as_view(), name='update_year'),
    path('delete_year/<int:pk>/', DeleteYearListView.as_view(), name='delete_year'),
    path('reorder_years/', reorder_years, name='reorder_years'),

    # GROUP
    path('group_list/', GroupListView.as_view(), name='group_list'),
    path('add_group/', GroupCreateView.as_view(), name='add_group'),
    path('update_group/<int:pk>/', GroupUpdateView.as_view(), name='update_group'),
    path('delete_confirm_group/<int:pk>/', GroupDeleteView.as_view(), name='delete_confirm_group'),

    # FƏNN
    path('subject_list/', SubjectListView.as_view(), name='subject_list'),
    path('add_subject/', SubjectCreateView.as_view(), name='add_subject'),
    path('update_subject/<int:pk>/', SubjectUpdateView.as_view(), name='update_subject'),
    path('delete_confirm_subject/<int:pk>/', SubjectDeleteView.as_view(), name='delete_confirm_subject'),

    # EXAM
    path('exam_list/', ExamListView.as_view(), name='exam_list'),
    path('add_exam/', ExamCreateView.as_view(), name='add_exam'),
    path('update_exam/<int:pk>/', ExamUpdateView.as_view(), name='update_exam'),
    path('delete_confirm_exam/<int:pk>/', ExamDeleteView.as_view(), name='delete_confirm_exam'),

    # CLASS-NUMBER
    path('class_number_list/', ClassNumberListView.as_view(), name='class_number_list'),
    path('add_class_number/', ClassNumberCreateView.as_view(), name='add_class_number'),
    path('update_class_number/<int:pk>/', ClassNumberUpdateView.as_view(), name='update_class_number'),
    path('delete_confirm_class_number/<int:pk>/', ClassNumberDeleteView.as_view(), name='delete_confirm_class_number'),

    # POSITIONS
    path('positions_list/', PositionListView.as_view(), name='positions_list'),
    path('add_position/', PositionCreateView.as_view(), name='add_position'),
    path('update_position/<int:pk>/', PositionUpdateView.as_view(), name='update_position'),
    path('delete_confirm_position/<int:pk>/', PositionDeleteView.as_view(), name='delete_confirm_position'),

    # PROXIMITY
    path('proximity_list/', ProximityListView.as_view(), name='proximity_list'),
    path('add_proximity/', ProximityCreateView.as_view(), name='add_proximity'),
    path('update_proximity/<int:pk>/', ProximityUpdateView.as_view(), name='update_proximity'),
    path('delete_confirm_proximity/<int:pk>/', ProximityDeleteView.as_view(), name='delete_confirm_proximity'),

    # REPORT
    path('late_payments/', LatePaymentListView.as_view(), name='late_payments'),
    path('export_late_payments/', ExportLatePaymentsExcelView.as_view(), name='export_late_payments'),
    path('daly_payments/', DailyPayments.as_view(), name='daly_payments'),
    path('export_daily_payments/', ExportDailyPaymentsExcelView.as_view(), name='export_daily_payments'),
    path('student_report/', StudentReportListView.as_view(), name='student_report'),
    path('export_student_report/', ExportStudentReportExcelView.as_view(), name='export_student_report'),
]

student/views.py
import os
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ObjectDoesNotExist
from openpyxl import Workbook
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
import logging
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from dateutil.relativedelta import relativedelta

from accounting.models import DocumentTemplate
from .filters import StudentFilter
from .forms import (
    StudentForm, SplitTuitionFeeForm, StudentSearchForm
)
from .models import (
    Student, TuitionFeeSplit, Year, StudentClass, Group, ClassNumber, Subject, Exam
)
from django.db import models

logger = logging.getLogger(__name__)


@login_required
def export_students(request):
    field_display_names = {
        'year': 'Tədris ili',
        'work_number': 'İş nömrəsi',
        'first_name': 'Ad',
        'last_name': 'Soyad',
        'gender': 'Cins',
        'shift': 'Növbə',
        'student_class': 'Sinif',
        'group': 'Qrup',
        'class_number': 'Sinif kodu',
        'section': 'Bölmə',
        'registration_status': 'Qeydiyyat statusu',
        'registration_type': 'Qeydiyyat növü',
        'score': 'Qəbul balı',
        'school': 'Məktəb',
        'city': 'Şəhər',
        'address': 'Ünvan',
        'father_first_name': 'Atanın adı',
        'father_last_name': 'Atanın soyadı',
        'father_sur_name': 'Atanın ata adı',
        'father_workplace': 'Atanın iş yeri',
        'father_position': 'Atanın vəzifəsi',
        'father_phone_1': 'Atanın telefonu 1',
        'father_phone_2': 'Atanın telefonu 2',
        'mather_first_name': 'Ananın adı',
        'mather_last_name': 'Ananın soyadı',
        'mather_sur_name': 'Ananın ata adı',
        'mather_workplace': 'Ananın iş yeri',
        'mather_position': 'Ananın vəzifəsi',
        'mather_phone_1': 'Ananın telefonu 1',
        'mather_phone_2': 'Ananın telefonu 2',
        'responsible_first_name': 'Məsul şəxs adı',
        'responsible_last_name': 'Məsul şəxs soyadı',
        'responsible_sur_name': 'Məsul şəxs ata adı',
        'responsible_passport_number': 'Məsul şəxs vəsiqə nömrəsi',
        'responsible_fin': 'Məsul şəxs vəsiqə FİN',
        'responsible_workplace': 'Məsul şəxs iş yeri',
        'responsible_position': 'Məsul şəxs vəzifəsi',
        'proximity': 'Məsul şəxs yaxınlığı',
        'responsible_phone_1': 'Məsul şəxs telefonu 1',
        'responsible_phone_2': 'Məsul şəxs telefonu 2',
        'annual_fee': 'İllik ödəniş',
        'created_at': 'Əlavə tarixi',
        'update': 'Yenilənə tarixi',
        'is_split_edited': 'Bölüşdürmə redaktəsi',
        'is_debtor': 'Borclu'
    }

    if request.method == 'POST':
        fields = request.POST.getlist('fields')
        filter_data = request.POST.dict()
        filter_data.pop('fields', None)
        filter_data.pop('csrfmiddlewaretoken', None)

        queryset = Student.objects.all()

        year = request.POST.get('year')
        work_number = request.POST.get('work_number__icontains')
        first_name = request.POST.get('first_name__icontains')
        last_name = request.POST.get('last_name__icontains')
        gender = request.POST.get('gender')
        shift = request.POST.get('shift')
        student_class = request.POST.get('student_class_hidden', '').split(',') if request.POST.get(
            'student_class_hidden') else []
        group = request.POST.get('group_hidden', '').split(',') if request.POST.get('group_hidden') else []
        class_number = request.POST.get('class_number')
        section = request.POST.get('section')
        registration_status = request.POST.get('registration_status')
        registration_type = request.POST.get('registration_type')
        created_at__gte = request.POST.get('created_at__gte')
        created_at__lte = request.POST.get('created_at__lte')

        # Применение фильтров к queryset
        if year:
            queryset = queryset.filter(year_id=year)
        if work_number:
            queryset = queryset.filter(work_number__icontains=work_number)
        if first_name:
            queryset = queryset.filter(first_name__icontains=first_name)
        if last_name:
            queryset = queryset.filter(last_name__icontains=last_name)
        if gender:
            queryset = queryset.filter(gender=gender)
        if shift:
            queryset = queryset.filter(shift=shift)
        if student_class:
            queryset = queryset.filter(student_class_id__in=student_class)
        if group:
            queryset = queryset.filter(group_id__in=group)
        if class_number:
            queryset = queryset.filter(class_number_id=class_number)
        if section:
            queryset = queryset.filter(section=section)
        if registration_status:
            queryset = queryset.filter(registration_status=registration_status)
        if registration_type:
            queryset = queryset.filter(registration_type=registration_type)
        if created_at__gte:
            queryset = queryset.filter(created_at__gte=created_at__gte)
        if created_at__lte:
            queryset = queryset.filter(created_at__lte=created_at__lte)

        students = queryset

        wb = Workbook()
        ws = wb.active
        ws.title = 'Students'

        headers = [field_display_names.get(field, field.replace('_', ' ').title()) for field in fields]
        ws.append(headers)

        for student in students:
            row = []
            for field in fields:
                value = getattr(student, field)
                if isinstance(value, models.Model):
                    value = str(value)
                elif isinstance(student._meta.get_field(field), models.ForeignKey):
                    related_object = getattr(student, field)
                    value = str(related_object)
                elif field in ['section', 'registration_status', 'registration_type']:
                    value = getattr(student, f'get_{field}_display')()
                elif isinstance(value, timezone.datetime):
                    value = value.replace(tzinfo=None)
                row.append(value)
            ws.append(row)

        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'attachment; filename=sagirler.xlsx'
        wb.save(response)
        return response

    excluded_fields = {'id', 'update', 'is_split_edited', 'is_debtor'}
    fields = [(field.name, field_display_names.get(field.name, field.name.replace('_', ' ').title()))
              for field in Student._meta.fields if field.name not in excluded_fields]
    return render(request, 'export_students.html', {'fields': fields})


@require_POST
def calculate_fee(request):
    student_class_id = request.POST.get('student_class')
    group_id = request.POST.get('group')
    subject_ids = request.POST.getlist('subject[]')
    exam_ids = request.POST.getlist('exam[]')

    total_fee = 0

    if student_class_id:
        student_class = StudentClass.objects.get(id=student_class_id)
        total_fee += student_class.price or 0

    if group_id:
        group = Group.objects.get(id=group_id)
        total_fee += group.price or 0

    if subject_ids:
        subjects = Subject.objects.filter(id__in=subject_ids)
        total_fee += sum(subject.price for subject in subjects if subject.price)

    if exam_ids:
        exams = Exam.objects.filter(id__in=exam_ids)
        total_fee += sum(exam.price for exam in exams if exam.price)

    return JsonResponse({'total_fee': total_fee})


def download_contract(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    file_path = os.path.join(settings.MEDIA_ROOT, f'contracts/{student.work_number}_contract.docx')

    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(),
                                    content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document')
            response['Content-Disposition'] = f'attachment; filename={os.path.basename(file_path)}'
            return response
    else:
        return HttpResponse("Müqavilə tapılmadı!", status=404)


class BaseStudentListView(LoginRequiredMixin, ListView):
    model = Student
    context_object_name = 'students'
    paginate_by = 20

    def get_default_category(self):
        """
        Этот метод предназначен для получения и кэширования значения по умолчанию для категории.
        Это позволяет избежать повторных запросов к базе данных.
        :return:
        """
        if not hasattr(self, '_default_category'):
            self._default_category = Year.objects.values_list('id', flat=True).first()
        return self._default_category

    def get_years(self):
        if not hasattr(self, '_years'):
            self._years = list(Year.objects.all())
        return self._years

    def get_queryset(self):
        queryset = super().get_queryset().select_related('student_class', 'group', 'class_number').prefetch_related(
            'tuitionfeesplit_set')
        data = self.request.GET.copy()
        data.setdefault('year', self.get_default_category())
        self.filterset = StudentFilter(data, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        additional_context = self.get_additional_context_data()
        context.update(additional_context)

student/templates/student/parameters/class_number/add_class_number.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Yeni sinif kodu
{% endblock %}
{% block content %}
<div class="container">
    <ol class="breadcrumb text-white bg-secondary bg-gradient border-0">
        <li class="breadcrumb-item"><a href="{% url 'student:student_list' %}"><span>ŞAGİRD CƏDVƏLİ</span></a></li>
        <li class="breadcrumb-item"><a href="{% url 'student:class_number_list' %}"><span>SİNİF KODU CƏDVƏLİ</span></a></li>
        <li class="breadcrumb-item text-secondary"><span>YENİ SİNİF KODU</span></li>
    </ol>
    <h2 class="text-center">Yeni sinif kodu</h2>
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="d-flex flex-column">
                    <label class="form-label" for="{{ form.number.id_for_label }}">Sinif kodu
                        {{ form.number }}
                        <div class="invalid-feedback">Bu sahə vacibdir!</div>
                    </label>
                </div>
                <div class="text-center">
                    <button class="btn btn-success btn-sm" type="submit">Yadda saxla</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

student/templates/student/parameters/class_number/class_number_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Sinif kodu cədvəli
{% endblock %}
{% block content %}
<div class="container">
    {% include 'accounting/inc/_messages.html' %}
    <ol class="breadcrumb text-white bg-secondary bg-gradient border-0">
        <li class="breadcrumb-item"><a href="{% url 'student:student_list' %}"><span>ŞAGİRD CƏDVƏLİ</span></a></li>
        <li class="breadcrumb-item text-secondary"><span>SİNİF KODU CƏDVƏLİ</span></li>
    </ol>
    <h2 class="text-center">Sinif kodu cədvəli</h2>
    <div class="row">
        <div class="col"><a class="btn btn-success btn-sm mb-2" role="button" href="{% url 'student:add_class_number' %}">Yeni sinif kodu</a></div>
        <div class="col-md-12">
            <div class="table-responsive text-nowrap">
                <table class="table table-hover">
                    <caption>Table Caption</caption>
                    <thead class="text-nowrap text-bg-secondary">
                    <tr>
                        <th>#</th>
                        <th>
                            <span style="font-weight: normal !important; color: rgb(33, 37, 41); background-color: var(--bs-table-bg);">Sinif kodu</span><br>
                        </th>
                        <th class="text-end">
                            <span  style="font-weight: normal !important; color: rgb(33, 37, 41); background-color: var(--bs-table-bg);">Əməliyyatlar</span><br>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for class_number in class_numbers %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ class_number.number }}</td>
                        <td class="text-end">
                            <a href="{% url 'student:update_class_number' class_number.id %}" class="btn btn-primary btn-sm me-2" role="button" data-bs-toggle="tooltip" data-bss-tooltip="" title="Redakte et">
                                <i class="fas fa-pen-alt"></i>
                            </a>
                            <a href="{% url 'student:delete_confirm_class_number' class_number.id %}" class="btn btn-danger btn-sm me-2" role="button" data-bs-toggle="tooltip" data-bss-tooltip="" title="Sil">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

student/templates/student/parameters/class_number/delete_confirm_class_number.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Sinfin silinməsi
{% endblock %}
{% block content %}
<div class="container">
    {% include 'accounting/inc/_messages.html' %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 col-sm-8">
                <form class="shadow p-5 bg-white rounded" method="post">
                    {% csrf_token %}
                    <div class="text-center mb-3">
                        <i class="fas fa-exclamation-triangle text-danger fa-2x"></i>
                    </div>
                    <h2 class="fw-bold text-center text-danger mb-3">XƏBƏRDARLIQ</h2>
                    <p class="text-center mb-3">Məlumatları sildikdən sonra bərpa edə bilməyəcəksiniz!</p>
                    <p class="text-center mb-4">Silmək istədiyinizdən əminsiniz?</p>
                    <div class="d-flex justify-content-between">
                        <a href="{% url 'student:class_number_list' %}"
                           class="btn btn-outline-secondary border rounded-0 border-secondary flex-grow-1 me-3"
                           type="button">XEYR</a>
                        <button class="btn btn-danger flex-grow-1" type="submit">BƏLİ</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

student/templates/student/parameters/class_number/update_class_number.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Sinif kodu redakte
{% endblock %}
{% block content %}
<div class="container">
    <ol class="breadcrumb text-white bg-secondary bg-gradient border-0">
        <li class="breadcrumb-item"><a href="{% url 'student:student_list' %}"><span>ŞAGİRD CƏDVƏLİ</span></a></li>
        <li class="breadcrumb-item"><a href="{% url 'student:exam_list' %}"><span>SİNİF KODU CƏDVƏLİ</span></a>
        </li>
        <li class="breadcrumb-item text-secondary"><span>SİNİF KODU REDAKTE</span></li>
    </ol>
    <h2 class="text-center">Sinif kodu redakte</h2>
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="d-flex flex-column">
                    <label class="form-label" for="{{ form.number.id_for_label }}">Sinif kodu
                        {{ form.number }}
                        <div class="invalid-feedback">Bu sahə vacibdir!</div>
                    </label>
                </div>
                <div class="text-center">
                    <button class="btn btn-success btn-sm" type="submit">Yenilə</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}