accounting/urls.py
from django.urls import path
from .views import (
    user_login, logout_view, profile_update, ContractListView, UploadContractView, DeleteContractView, change_password
)


app_name = 'accounting'

urlpatterns = [
    path('', user_login, name='login'),
    path('logout_view/', logout_view, name='logout_view'),
    path('profile/', profile_update, name='profile_update'),
    path('change-password/', change_password, name='change_password'),
    path('contract_list/', ContractListView.as_view(), name='contract_list'),
    path('upload_contract/', UploadContractView.as_view(), name='upload_contract'),
    path('delete_confirm_contract/<int:pk>/', DeleteContractView.as_view(), name='delete_confirm_contract'),
]

handler404 = 'accounting.views.page_not_found'

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounting.urls', namespace='accounting')),
    path('', include('student.urls', namespace='student')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from .parameters_views import (
    ClassListView,
    ClassListCreateView,
    ClassListUpdateView,
    DeleteClassListView,
    YearListView,
    YearCreateView,
    YearUpdateView,
    DeleteYearListView,
    reorder_years,
    GroupDeleteView,
    GroupUpdateView,
    GroupCreateView,
    GroupListView, SubjectDeleteView, SubjectUpdateView, SubjectCreateView, SubjectListView, ExamListView,
    ExamCreateView, ExamUpdateView, ExamDeleteView, ClassNumberListView, ClassNumberCreateView, ClassNumberUpdateView,
    ClassNumberDeleteView, PositionListView, PositionCreateView, PositionUpdateView, PositionDeleteView,
    ProximityListView, ProximityCreateView, ProximityUpdateView, ProximityDeleteView
)
from .report_views import (
    LatePaymentListView, ExportLatePaymentsExcelView, DailyPayments, ExportDailyPaymentsExcelView,
    StudentReportListView, ExportStudentReportExcelView

)
from .views import (
    CreateStudentView,
    StudentListView,
    SplitTuitionFeeView,
    TuitionFeeSplitDetailView,
    refund_payment,
    PaymentReceiptView,
    save_splits,
    make_payment,
    export_students,
    RepeatRegistrationSearchView,
    RepeatRegistrationCreateView, calculate_fee, StudentUpdateView, download_contract, StudentDeleteConfirm,
    tuition_fee_schedule_view
)

app_name = 'student'
urlpatterns = [
    # STUDENT
    path('student_list/', StudentListView.as_view(), name='student_list'),
    path('add_student/', CreateStudentView.as_view(), name='add_student'),
    path('update_student/<int:pk>/', StudentUpdateView.as_view(), name='update_student'),
    path('repeat_registration_search/', RepeatRegistrationSearchView.as_view(),
         name='repeat_registration_search'),
    path('repeat_registration_create/<int:student_id>/', RepeatRegistrationCreateView.as_view(),
         name='repeat_registration_create'),
    path('export_students/', export_students, name='export_students'),
    path('calculate-fee/', calculate_fee, name='calculate_fee'),
    path('student/<int:student_id>/download_contract/', download_contract, name='download_contract'),
    path('student_delete_confirm/<int:pk>/', StudentDeleteConfirm.as_view(), name='student_delete_confirm'),

    # PAYMENT
    path('student/<int:student_id>/split/', SplitTuitionFeeView.as_view(), name='split_tuition_fee'),
    path('student/split/<int:student_id>/', TuitionFeeSplitDetailView.as_view(), name='tuition_fee_split_detail'),
    path('student/make_payment/<int:split_id>/', make_payment, name='make_payment'),

    path('student/refund_payment/<int:split_id>/', refund_payment, name='refund_payment'),
    path('student/payment_receipt/<int:split_id>/', PaymentReceiptView.as_view(), name='payment_receipt'),
    path('student/save_splits/<int:student_id>/', save_splits, name='save_splits'),
    path('students/<int:student_id>/tuition-fee-schedule/', tuition_fee_schedule_view, name='tuition_fee_schedule'),

    # PARAMETERS
    # ***CLASS-LIST***
    path('class_list/', ClassListView.as_view(), name='class_list'),
    path('add_class/', ClassListCreateView.as_view(), name='add_class'),
    path('update_class/<int:pk>/', ClassListUpdateView.as_view(), name='update_class'),
    path('delete_confirm_class/<int:pk>/', DeleteClassListView.as_view(), name='delete_confirm_class'),

    # ***YEAR-LIST***
    path('year_list/', YearListView.as_view(), name='year_list'),
    path('add_year/', YearCreateView.as_view(), name='add_year'),
    path('update_year/<int:pk>/', YearUpdateView.as_view(), name='update_year'),
    path('delete_year/<int:pk>/', DeleteYearListView.as_view(), name='delete_year'),
    path('reorder_years/', reorder_years, name='reorder_years'),

    # GROUP
    path('group_list/', GroupListView.as_view(), name='group_list'),
    path('add_group/', GroupCreateView.as_view(), name='add_group'),
    path('update_group/<int:pk>/', GroupUpdateView.as_view(), name='update_group'),
    path('delete_confirm_group/<int:pk>/', GroupDeleteView.as_view(), name='delete_confirm_group'),

    # FƏNN
    path('subject_list/', SubjectListView.as_view(), name='subject_list'),
    path('add_subject/', SubjectCreateView.as_view(), name='add_subject'),
    path('update_subject/<int:pk>/', SubjectUpdateView.as_view(), name='update_subject'),
    path('delete_confirm_subject/<int:pk>/', SubjectDeleteView.as_view(), name='delete_confirm_subject'),

    # EXAM
    path('exam_list/', ExamListView.as_view(), name='exam_list'),
    path('add_exam/', ExamCreateView.as_view(), name='add_exam'),
    path('update_exam/<int:pk>/', ExamUpdateView.as_view(), name='update_exam'),
    path('delete_confirm_exam/<int:pk>/', ExamDeleteView.as_view(), name='delete_confirm_exam'),

    # CLASS-NUMBER
    path('class_number_list/', ClassNumberListView.as_view(), name='class_number_list'),
    path('add_class_number/', ClassNumberCreateView.as_view(), name='add_class_number'),
    path('update_class_number/<int:pk>/', ClassNumberUpdateView.as_view(), name='update_class_number'),
    path('delete_confirm_class_number/<int:pk>/', ClassNumberDeleteView.as_view(), name='delete_confirm_class_number'),

    # POSITIONS
    path('positions_list/', PositionListView.as_view(), name='positions_list'),
    path('add_position/', PositionCreateView.as_view(), name='add_position'),
    path('update_position/<int:pk>/', PositionUpdateView.as_view(), name='update_position'),
    path('delete_confirm_position/<int:pk>/', PositionDeleteView.as_view(), name='delete_confirm_position'),

    # PROXIMITY
    path('proximity_list/', ProximityListView.as_view(), name='proximity_list'),
    path('add_proximity/', ProximityCreateView.as_view(), name='add_proximity'),
    path('update_proximity/<int:pk>/', ProximityUpdateView.as_view(), name='update_proximity'),
    path('delete_confirm_proximity/<int:pk>/', ProximityDeleteView.as_view(), name='delete_confirm_proximity'),

    # REPORT
    path('late_payments/', LatePaymentListView.as_view(), name='late_payments'),
    path('export_late_payments/', ExportLatePaymentsExcelView.as_view(), name='export_late_payments'),
    path('daly_payments/', DailyPayments.as_view(), name='daly_payments'),
    path('export_daily_payments/', ExportDailyPaymentsExcelView.as_view(), name='export_daily_payments'),
    path('student_report/', StudentReportListView.as_view(), name='student_report'),
    path('export_student_report/', ExportStudentReportExcelView.as_view(), name='export_student_report'),
]

accounting/models.py
from django.db import models


class DocumentTemplate(models.Model):
    CLASS_CHOICES = [
        ('standard', 'Digər'),
        ('0', 'Məktəbəqədər'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
        ('11', '11'),
    ]

    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='document_templates/')
    class_level = models.CharField(max_length=10, choices=CLASS_CHOICES, default='standard')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.uploaded_at}"

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name = "Müqavilə"
        verbose_name_plural = "Müqavilə"

accounting/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User

from accounting.models import DocumentTemplate


class LoginForm(forms.Form):
    """
    Простая форма для входа в систему.
    Поля: username, password.
    """
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'id_old_password', 'name': 'old_password',
                                          'aria-describedby': 'toggleOldPassword'}),
    )
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'id_new_password1', 'name': 'new_password1',
                                          'aria-describedby': 'toggleNewPassword1'}),
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'id_new_password2', 'name': 'new_password2',
                                          'aria-describedby': 'toggleNewPassword2'}),
    )


class DocumentTemplateForm(forms.ModelForm):
    class Meta:
        model = DocumentTemplate
        fields = ['name', 'file', 'class_level']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'class_level': forms.Select(attrs={'class': 'form-control'}),
            'file': forms.FileInput(attrs={'class': 'form-control'}),
        }

accounting/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounting.forms import LoginForm, ProfileForm, CustomPasswordChangeForm, DocumentTemplateForm
from accounting.models import DocumentTemplate


def page_not_found(request, exception):
    return render(request, 'accounting/404.html', {}, status=404)


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None and user.is_active:
                login(request, user)
                messages.success(request, 'Uğurla daxil oldunuz!')
                return redirect('student:student_list')
            else:
                messages.error(request, f"Xəta: İstifadəçi adı və ya şifrə yalışdır! Məlumatları bir daha yoxlayın.")
    else:
        form = LoginForm()
    return render(request, 'accounting/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('accounting:login')


@login_required
def profile_update(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profil uğurla yeniləndi!')
            return redirect('accounting:profile_update')
    else:
        profile_form = ProfileForm(instance=request.user)

    return render(request, 'accounting/profile.html', {
        'profile_form': profile_form,
    })


@login_required
def change_password(request):
    if request.method == 'POST':
        password_form = CustomPasswordChangeForm(user=request.user, data=request.POST)
        if password_form.is_valid():
            password_form.save()
            update_session_auth_hash(request, password_form.user)  # Обновляем сессию пользователя
            messages.success(request, 'Şifrə uğurla dəyişdirildi!')
            return redirect('accounting:change_password')
    else:
        password_form = CustomPasswordChangeForm(user=request.user)

    return render(request, 'accounting/change_password.html', {
        'password_form': password_form,
    })


class ContractListView(LoginRequiredMixin, ListView):
    model = DocumentTemplate
    context_object_name = 'templates'
    template_name = 'accounting/contract_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UploadContractView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = DocumentTemplate
    form_class = DocumentTemplateForm
    template_name = 'accounting/upload_contract.html'
    success_url = reverse_lazy('accounting:contract_list')
    success_message = 'Müqavilə uğurla yükləndi'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        return context


class DeleteContractView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = DocumentTemplate
    template_name = 'accounting/delete_confirm_contract.html'
    success_url = reverse_lazy('accounting:contract_list')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        return context

accounting/templates/accounting/inc/_footer.html
<footer class="text-center py-4 justify-content-end">
    <div class="container">
        <div class="row row-cols-1 row-cols-lg-3">
            <div class="col">
                <p class="text-muted my-2">Copyright © 2024 Brand</p>
            </div>
            <div class="col">
                <ul class="list-inline my-2">
                    <li class="list-inline-item me-4">
                        <div class="bs-icon-circle bs-icon-primary bs-icon"><svg class="bi bi-facebook" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
                            </svg></div>
                    </li>
                    <li class="list-inline-item me-4">
                        <div class="bs-icon-circle bs-icon-primary bs-icon"><svg class="bi bi-twitter" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
                            </svg></div>
                    </li>
                    <li class="list-inline-item">
                        <div class="bs-icon-circle bs-icon-primary bs-icon"><svg class="bi bi-instagram" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
                            </svg></div>
                    </li>
                </ul>
            </div>
            <div class="col">
                <ul class="list-inline my-2">
                    <li class="list-inline-item"><a class="link-secondary" href="#">Privacy Policy</a></li>
                    <li class="list-inline-item"><a class="link-secondary" href="#">Terms of Use</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

accounting/templates/accounting/inc/_messages.html
{% comment %}

<div class="col-12 .msg-container">
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="alert alert-success msg msg-success" role="alert">
                    {{ message }}
                </div>
            {% elif message.tags == 'error' %}
                <div class="alert alert-danger msg msg-error" role="alert">
                    {{ message }}
                </div>
            {% elif message.tags == 'warning' %}
                <div class="alert alert-warning msg msg-warning" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
{% endcomment %}
{% if messages %}
    <script>
        {% for message in messages %}
            Swal.fire({
                icon: '{{ message.tags }}',
                title: '{{ message }}',
                showConfirmButton: true,
                timer: 3000
            });
        {% endfor %}
    </script>
{% endif %}

accounting/templates/accounting/inc/_nav.html
{% load static %}
<nav class="navbar navbar-light navbar-expand-xl sticky-top shadow py-3 mb-5">

    <div class="container">
        <a href="{% url 'student:student_list' %}" class="me-3"><img src="{% static 'assets/img/logo/default.svg' %}" width="50" alt=""></a>
        <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1">
            <span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link {% if 'student_list' in request.resolver_match.url_name %}active{% endif %}" href="{% url 'student:student_list' %}">Qeydiyyat</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Şagird parameterləri</a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'student:class_list' %}">Siniflər</a></li>
                    <li><a class="dropdown-item" href="{% url 'student:group_list' %}">Qruplar</a></li>
                    <li><a class="dropdown-item" href="{% url 'student:class_number_list' %}">Sinif kodları</a></li>
                    <li><a class="dropdown-item" href="{% url 'student:subject_list' %}">Fənlər</a></li>
                    <li><a class="dropdown-item" href="{% url 'student:year_list' %}">Tədris illəri</a></li>
                    <li><a class="dropdown-item" href="{% url 'student:exam_list' %}">İmtahanlar</a></li>
                    <li><a class="dropdown-item" href="{% url 'student:positions_list' %}">Vəzifələr</a></li>
                    <li><a class="dropdown-item" href="{% url 'student:proximity_list' %}">Yaxınlıq</a></li>
                    <li><a class="dropdown-item" href="{% url 'accounting:contract_list' %}">Müqavilələr</a></li>
                  </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Hesabatlar</a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item dropdown-item-custom mb-2" href="{% url 'student:student_report' %}">Şagirdlər üzrə hesabat</a></li>
                    <li><a class="dropdown-item dropdown-item-custom mb-2" href="{% url 'student:daly_payments' %}">Gündəlik ödənişlər</a></li>
                    <li><a class="dropdown-item dropdown-item-custom" href="{% url 'student:late_payments' %}">Gecikən ödənişlər</a></li>
                  </ul>
            </li>

            </ul>
            <div class="d-flex">
                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">Parameterlər</button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{% url 'accounting:profile_update' %}"><i class="fas fa-user-cog"></i> Profili dəyiş</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounting:change_password' %}"><i class="fas fa-user-lock"></i> Şifrəni dəyiş</a></li>
                        <li><a href="{% url 'accounting:logout_view' %}" class="dropdown-item btn btn-secondary btn-sm" type="button"><i class="fas fa-sign-out-alt me-2"></i>Çıxış</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>

accounting/templates/accounting/inc/_pagination.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" tabindex="-1">Birinci</a>
        </li>
        {% endif %}

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Əvvəlki</a>
        </li>
        {% endif %}

        {% for p in page_obj.paginator.page_range %}

        {% if page_obj.number == p %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ p }}">{{ p }} <span class="sr-only">(current)</span></a>
        </li>
        {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
        <li class="page-item">
            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Sonrakı</a>
        </li>
        {% endif %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Sonuncu</a>
        </li>
        {% endif %}

    </ul>
</nav>
{% endif %}